# permissions for end users to edit fluxshardsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: fluxshardset-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: flux-shard-controller
    app.kubernetes.io/part-of: flux-shard-controller
    app.kubernetes.io/managed-by: kustomize
  name: fluxshardset-editor-role
rules:
- apiGroups:
  - templates.weave.works
  resources:
  - fluxshardsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templates.weave.works
  resources:
  - fluxshardsets/status
  verbs:
  - get
